name: plosokerep_apk
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  adhan_dart: ^1.1.2
  file_picker: ^8.1.3
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  syncfusion_flutter_pdfviewer: ^27.1.57

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - image/LOGO1.png
  - image/logo.png
  - image/masjid.jpg
  - image/map.png
  - image/aparatur.png
  - image/info desa.png
  - image/kontak desa.png
  - image/depan desa.png
  - image/visimisi.png
  - image/visimisi2.png
  - image/sejarah desa.png
  - image/customer service.png
  - image/aparatur2.png
  - image/struktur.png
  - assets/Sejarah Desa Plosokerep.pdf
  - assets/Visi.pdf
  - assets/Misi.pdf
  - image/Pengajuan.png
  - image/Pengajuan2.png
  - image/Pengaduan.png
  - image/Pengaduan2.png
  - image/umkm map.png
  - image/berita a.jpg
  - image/berita b.jpg